kind: pipeline
name: default

steps:
  - name: dco
    group: meta
    image: algernon/drone-plugin-dco

  - name: signature-check
    group: meta
    image: algernon/drone-plugin-signature-check
    keys: [10E65DC045EABEFCC5193A26AC1E90BAC433F68F]
    when:
      event: tag

  - name: publish
    image: plugins/docker
    settings:
      repo: algernon/writefreely
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      ref:
        include:
          - refs/heads/master
          - refs/tags/**
